# source me!

export LOG_LEVEL=DEBUG
export SUPPORT_MESSAGE_RESEND_TIMEOUT=5
export API_PORT=31235
export RESPONSE_ROUTER_EP=127.0.0.1:8888
export RESPONSE_ROUTER_API=/api/functions/
export RECEIVER_BROKER_TOPIC=MYTEST